version: "3.8"

# Enable BuildKit for enhanced caching
x-build-args: &build-args
  BUILDKIT_INLINE_CACHE: 1
services:
  db:
    image: mysql:8.0
    container_name: vacation_mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: vacation_db
    volumes:
      - db_data:/var/lib/mysql
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
      # Enable caching using local layers instead of registry
      args:
        <<: *build-args
    container_name: vacation_backend
    restart: unless-stopped
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: vacation_db
      JWT_SECRET: "supersecretjwt"
      # Internal endpoint for backend to upload to S3
      S3_ENDPOINT: "http://localstack:4566"
      # Public endpoint for frontend clients to access S3 objects
      S3_PUBLIC_ENDPOINT: "http://localhost:4566"
      S3_BUCKET: "vacations"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
    ports:
      - "3000:3000"
    volumes:
      - ./Backend/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
      localstack:
        condition: service_started

  frontend:
    build: ./Frontend
    container_name: vacation_frontend
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_API_URL=http://localhost:3000/api

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    restart: unless-stopped
    ports:
      - "4566:4566"                     # LocalStack Gateway (make accessible from other containers)
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
      - "127.0.0.1:53:53"                # DNS configuration (TCP)
      - "127.0.0.1:53:53/udp"            # DNS configuration (UDP)
      - "127.0.0.1:443:443"              # LocalStack HTTPS Gateway
    networks:
      - app-network
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - HOSTNAME_EXTERNAL=localstack
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
